
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsdeploy
  labels:
    app: nodejstest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejstest
  template:
    metadata:
      labels:
        app: nodejstest 
    spec:
      containers:
      - name: nodeserver
        image: iamsahil84/nodeapp:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodejstest
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
