apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sworker1
spec:
  selector:
    matchLabels:
      app: w1
  template:
    metadata:
      labels:
        app: w1
    spec:
      hostNetwork: true  # Use the node's network instead of containers
      containers:
      - name: workernode1
        image: centos:latest
        command: ["/bin/bash", "-c", "--"]    # Keeps container alive
        args: ["while true; do sleep 30; done;"]  # Infinite loop to prevent container exit
        volumeMounts:
        - mountPath: /etc/sysconfig/network-scripts
          name: workernode1-storage
      volumes:
      - name: workernode1-storage
        persistentVolumeClaim:
          claimName: workernode1-pvc 